token: 00000000000000
suggestion:
  channel: 00000000000000
  thumbnail: NONE
announcement:
  channel: 00000000
  thumbnail: NONE # NONE means no thumbnail will be sent
Logs:
  tpschannel: 0000
  memberjoin: 0000
  memberleave: 0000
  tpswarnchannel: 00000
  banchannel: 0000000
embeds:
  - vote.yml
  - join.yml
  - leave.yml
data: